Models/ErrorViewModel.cs
using System;

namespace Calculadora_Web_Ejercicio_4.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Operaciones.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Calculadora_Web_Ejercicio_4.Models
{
    public class Operaciones
    {
        [Required]

        public double Valor1 { get; set; }

        [Required]
        public double Valor2 { get; set; }


        public double Resultado { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Calculadora_Web_Ejercicio_4.Models;
using static Calculadora_Web_Ejercicio_4.Models.Operaciones;

namespace Calculadora_Web_Ejercicio_4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Operaciones()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Operaciones operaciones, string Funtion)
        {
            float Total = 0;
            float V1 = Convert.ToSingle(operaciones.Valor1.ToString());
            float V2 = Convert.ToSingle(operaciones.Valor2.ToString());            

            switch (Funtion) {
                case "+":
                    Total = V1 + V2;
                    break;

                case "-":
                    Total = V1 - V2;
                    break;

                case "*":
                    Total = V1 * V2;
                    break;

                case "/":
                    Total = V1 / V2;
                    break;

                default:
                    Total = 0;
                    break;
            }
            ViewData["Resultado"] = Total;
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PotenciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Calculadora_Web_Ejercicio_4.Models;
using Microsoft.AspNetCore.Mvc;

namespace Calculadora_Web_Ejercicio_4.Controllers
{
    public class PotenciaController : Controller
    {
        public IActionResult PotenciaView()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PotenciaView(Operaciones operaciones, string Funtion)
        {
            Double Total = 0;
            Double V1 = operaciones.Valor1;
            Double V2 = operaciones.Valor2;
            Total = Math.Pow(V1, V2);

            ViewData["Resultado"] = Total;
            return View();
        }
    }
}

Controllers/RaicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Calculadora_Web_Ejercicio_4.Models;
using Microsoft.AspNetCore.Mvc;

namespace Calculadora_Web_Ejercicio_4.Controllers
{
    public class RaicesController : Controller
    {
        public IActionResult Raices()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Raices(Operaciones operaciones, string Funtion)
        {
            Double Total = 0;
            Double V1 = operaciones.Valor1;

            switch (Funtion)
            {
                case "sqrt":
                    Total = Math.Sqrt(V1);
                    break;

                case "cbrt":
                    Total = Math.Cbrt(V1);
                    break;
                default:
                    Total = 0;
                    break;
            }
            Total = (Math.Round((double)Total * 10000)) / 10000;
            ViewData["Resultado"] = Total;
            return View();
        }
    }
}

Controllers/TrigonometriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Calculadora_Web_Ejercicio_4.Models;
using Microsoft.AspNetCore.Mvc;

namespace Calculadora_Web_Ejercicio_4.Controllers
{
    public class TrigonometriaController : Controller
    {
        public IActionResult Trigonometria()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Trigonometria(Operaciones operaciones, string Funtion)
        {
            Double Total = 0;
            Double V1 = (operaciones.Valor1 * Math.PI)/180;
           
            switch (Funtion)
            {
                case "sen":
                    Total = Math.Sin(V1);
                    break;

                case "cos":
                    Total = Math.Cos(V1);
                    break;

                case "tan":
                    Total = Math.Tan(V1);
                    break;

                case "cot":
                    Total = 1/Math.Tan(V1);
                    break;

                case "sec":
                    Total = 1/Math.Cos(V1);
                    break;

                case "csc":
                    Total = 1/Math.Sin(V1);
                    break;

                default:
                    Total = 0;
                    break;
            }
            Total = (Math.Round((double)Total * 10000)) / 10000;
            ViewData["Resultado"] = Total;
            return View();
        }
    }
}

Views/Home/Index.cshtml
@model Operaciones

@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center">
    <h1 class="display-4">Calculadora Web</h1>
    <p>Operaciones Basicas</p>
</div>

<div class="form-group row">
    <div class="col-md-5">
        <form method="post">

            <div class="form-group">
                <label asp-for="Valor1" class="control-label">Primer Valor</label>
                <input asp-for="Valor1" class="form-control" required />
                <span asp-validation-for="Valor1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor2" class="control-label">Segundo Valor</label>
                <input asp-for="Valor2" class="form-control" required />
                <span asp-validation-for="Valor2" class="text-danger"></span>
            </div>
            <div class="col-5">

                <input type="radio" value="+" name="Funtion" required /><label class="font-weight-bold"> Sumar</label><br />
                <input type="radio" value="-" name="Funtion" required /><label class="font-weight-bold"> Restar</label><br />
                <input type="radio" value="*" name="Funtion" required /><label class="font-weight-bold"> Multiplicar</label><br />
                <input type="radio" value="/" name="Funtion" required /><label class="font-weight-bold"> Dividir</label><br />

            </div>


            <div class="form-group">
                <button type="submit" class="btn btn-primary">Calcular</button>
            </div>
        </form>
    </div>
    <div class="col-md-5 ">

        <h5 class="alert-primary">El Resultado es: @ViewData["Resultado"]</h5>
        <hr />
    </div>
</div>

Views/Home/Operaciones.cshtml
<div class="text-center">
    <h1 class="display-4">Operaciones<h1>
   
</div>
<div>
    <h4>Operaciones Basicas --  <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Ir</a></h4>
    <br />
    <h4>Operaciones Trigonometricas -- <a class="btn btn-primary" asp-controller="Trigonometria" asp-action="Trigonometria">Ir</a></h4>
    <br />

    <h4>Operacion Raíz -- <a class="btn btn-primary" asp-controller="Raices" asp-action="Raices">Ir</a></h4>
    <br />

    <h4>Operacion Potencia -- <a class="btn btn-primary" asp-controller="Potencia" asp-action="PotenciaView">Ir</a></h4>
    <br />
</div>

Views/Potencia/PotenciaView.cshtml
@model Operaciones

@{
    ViewData["Title"] = "Potencia";
}


<div class="text-center">
    <h1 class="display-4">Calculadora Web</h1>
    <p>Operacion Potencia</p>
</div>

<div class="form-group row">
    <div class="col-md-5">
        <form method="post">

            <div class="form-group">
                <label asp-for="Valor1" class="control-label">Valor</label>
                <input asp-for="Valor1" class="form-control" required />
                <span asp-validation-for="Valor1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor2" class="control-label">Elevado a</label>
                <input asp-for="Valor2" class="form-control" required />
                <span asp-validation-for="Valor2" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Calcular</button>
            </div>
        </form>
    </div>
    <div class="col-md-5 ">

        <h5 class="alert-primary">El Resultado es: @ViewData["Resultado"]</h5>
        <hr />
    </div>
</div>

Views/Raices/Raices.cshtml
@model Operaciones

@{
    ViewData["Title"] = "Raíz";
}


<div class="text-center">
    <h1 class="display-4">Calculadora Web</h1>
    <p>Operacion Raíz</p>
</div>

<div class="form-group row">
    <div class="col-md-5">
        <form method="post">

            <div class="form-group">
                <label asp-for="Valor1" class="control-label">Valor</label>
                <input asp-for="Valor1" class="form-control" required />
                <span asp-validation-for="Valor1" class="text-danger"></span>
            </div>

            <div class="col-5">
                <input type="radio" value="sqrt" name="Funtion" required /><label class="font-weight-bold"> Raíz Cuadrada</label><br />
                <input type="radio" value="cbrt" name="Funtion" required /><label class="font-weight-bold"> Raíz Cubica</label><br />                
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Calcular</button>
            </div>
        </form>
    </div>
    <div class="col-md-5 ">

        <h5 class="alert-primary">El Resultado es: @ViewData["Resultado"]</h5>
        <hr />
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calculadora_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Calculadora_Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Operaciones">Operaciones</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Calculadora Web - Héctor Sanchez 2018-6183
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Trigonometria/Trigonometria.cshtml
@model Operaciones

@{
    ViewData["Title"] = "Trigonometria";
}


<div class="text-center">
    <h1 class="display-4">Calculadora Web</h1>
    <p>Operaciones Trigonometrica</p>
</div>

<div class="form-group row">
    <div class="col-md-5">
        <form method="post">

            <div class="form-group">
                <label asp-for="Valor1" class="control-label">Valor</label>
                <input asp-for="Valor1" class="form-control" required />
                <span asp-validation-for="Valor1" class="text-danger"></span>
            </div>
            
            <div class="col-5">
                <input type="radio" value="sen" name="Funtion" required /><label class="font-weight-bold"> Seno</label><br />
                <input type="radio" value="cos" name="Funtion" required /><label class="font-weight-bold"> Coseno</label><br />
                <input type="radio" value="tan" name="Funtion" required /><label class="font-weight-bold"> Tangente</label><br />
                <input type="radio" value="cot" name="Funtion" required /><label class="font-weight-bold"> Cotangente</label><br />
                <input type="radio" value="sec" name="Funtion" required /><label class="font-weight-bold"> Secante</label><br />
                <input type="radio" value="csc" name="Funtion" required /><label class="font-weight-bold"> Cosecante</label><br />
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Calcular</button>
            </div>
        </form>
    </div>
    <div class="col-md-5 ">

        <h5 class="alert-primary">El Resultado es: @ViewData["Resultado"]</h5>
        <hr />
    </div>
</div>